use_frameworks!

platform :ios, '10.0'

target 'ZLTestModule3_Example' do
  pod 'ZLTestModule3', :path => '../'
  pod 'ZLProtoService', :path => '../../'

  target 'ZLTestModule3_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
