use_frameworks!

platform :ios, '10.0'

target 'ZLProtoService_Example' do
  pod 'ZLProtoService', :path => '../'

  target 'ZLProtoService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
