use_frameworks!

platform :ios, '10.0'

target 'ZLTestModule1_Example' do
  pod 'ZLTestModule1', :path => '../'
  pod 'ZLProtoService', :path => '../../'

  target 'ZLTestModule1_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
